### ISSUE TITLE
Flight duration does not factor timezone

### ISSUE THREAD

**Issue by briandotdev** [pbogre/jetlog#42] opened 2024-08-19 22:23 UTC
Hey this is really cool!  Thanks for sharing with the community.

I am on a flight currently. UA2360. Departure at 4:53 EST and arrival at 6:19 CST. Jetlog shows this as an 86 minute flight but it's actually a 146 minute flight when you factor the one hour timezone change. I'm thinking that the app is possibly not timezone aware at present time? Does the airport database that is being used carry a time zone field?

**Comment by pbogre** [comment] 2024-08-20 00:49
Thanks for the issue, but this is a duplicate of #32.

Currently Jetlog does not attempt to fetch any timezone, and the duration calculation is performed by assuming that the departure and arrival times are in the same time zone.

**Closed** 2024-08-20 00:49 UTC
