### ISSUE TITLE
Jetlog doesn't seem timezone aware

### ISSUE THREAD

**Issue by jamess60** [pbogre/jetlog#38] opened 2024-08-06 08:15 UTC
I have a 4900 mile flight with a 270 min duration (as I went back in time -6). The return flight on the same route shows 935 minute duration (because I went forward in time). 

Ideally, JetLog needs to know the timezone of each airport so it can factor the adjustment into durations

**Comment by pbogre** [comment] 2024-08-06 14:48
duplicate of #32

**Closed** 2024-08-06 14:48 UTC

**Comment by jamess60** [comment] 2024-08-06 16:41
Apologies, will update there
